
services:
  fastapi:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    container_name: statcollector_fastapi
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - ./.envs/.local/.fastapi
    depends_on:
      - redis
      - clickhouse

  redis:
    image: redis:latest
    container_name: statcollector_redis
    ports:
      - "6379:6379"
    env_file:
      - ./.envs/.local/.redis
    volumes:
      - redis_data:/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: statcollector_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    env_file:
      - ./.envs/.local/.clickhouse

  clickhouse-client:
    image: clickhouse/clickhouse-client
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    command: -c "tail -f /dev/null"
    depends_on:
      - clickhouse

volumes:
  redis_data:
  clickhouse_data:
